oauth_token = "KxSdRqdrOAmUGLrl-BRCPhwotomSfyrMd1y8pU66sIM.ul15fB9bHPoUK5m2nXI4di-G3YmAC_r7kZovtRqQPSc"
expiration_time = "2025-02-23T08:00:05.305Z"
refresh_token = "5xQ3HP4UIgUoC0bdHb-ZUz_h_jmamSF9RAaeAG3TL64.CFWJnK0F4RJrNPAiGvUOLKYrCUTml_ar92J2eUKhjFg"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "ai:write",
  "queues:write",
  "pipelines:write",
  "offline_access"
]
